export let Tabs = [
  {
    title: "Smartphone",
    description: "A high-end smartphone with a 6.5-inch OLED display, an octa-core processor, and a 48MP camera. It's perfect for users who want great performance, vibrant visuals, and reliable battery life. Its sleek design and cutting-edge technology make it a must-have device for tech enthusiasts and casual users alike. A high-end smartphone with a 6.5-inch OLED display, an octa-core processor, and a 48MP camera. It's perfect for users who want great performance, vibrant visuals, and reliable battery life. Its sleek design and cutting-edge technology make it a must-have device for tech enthusiasts and casual users alike. A high-end smartphone with a 6.5-inch OLED display, an octa-core processor, and a 48MP camera. It's perfect for users who want great performance, vibrant visuals, and reliable battery life. Its sleek design and cutting-edge technology make it a must-have device for tech enthusiasts and casual users alike. A high-end smartphone with a 6.5-inch OLED display, an octa-core processor, and a 48MP camera. It's perfect for users who want great performance, vibrant visuals, and reliable battery life. Its sleek design and cutting-edge technology make it a must-have device for tech enthusiasts and casual users alike."
  },
  {
    title: "Laptop",
    description: "This lightweight laptop offers an Intel i7 processor, 16GB RAM, and a 512GB SSD. It combines high performance with portability, ideal for work, entertainment, and creative projects. The clear 15.6-inch screen, long battery life, and solid build make it the perfect tool for multitasking and productivity on the go.This lightweight laptop offers an Intel i7 processor, 16GB RAM, and a 512GB SSD. It combines high performance with portability, ideal for work, entertainment, and creative projects. The clear 15.6-inch screen, long battery life, and solid build make it the perfect tool for multitasking and productivity on the go.This lightweight laptop offers an Intel i7 processor, 16GB RAM, and a 512GB SSD. It combines high performance with portability, ideal for work, entertainment, and creative projects. The clear 15.6-inch screen, long battery life, and solid build make it the perfect tool for multitasking and productivity on the go.This lightweight laptop offers an Intel i7 processor, 16GB RAM, and a 512GB SSD. It combines high performance with portability, ideal for work, entertainment, and creative projects. The clear 15.6-inch screen, long battery life, and solid build make it the perfect tool for multitasking and productivity on the go."
  },
  {
    title: "Headphones",
    description: "Over-ear wireless headphones featuring active noise cancellation and Bluetooth 5.0 connectivity. With superior sound quality and up to 30 hours of playback, these headphones offer comfort and style for long listening sessions. The foldable design makes them easy to carry, while the noise-canceling feature enhances the audio experience.Over-ear wireless headphones featuring active noise cancellation and Bluetooth 5.0 connectivity. With superior sound quality and up to 30 hours of playback, these headphones offer comfort and style for long listening sessions. The foldable design makes them easy to carry, while the noise-canceling feature enhances the audio experience.Over-ear wireless headphones featuring active noise cancellation and Bluetooth 5.0 connectivity. With superior sound quality and up to 30 hours of playback, these headphones offer comfort and style for long listening sessions. The foldable design makes them easy to carry, while the noise-canceling feature enhances the audio experience."
  }
];

  